### PR TITLE
pdftk used to fail if special characters are included in filenames

### PR DESCRIPTION
**Pull request by oganm**

### CODE REVIEW

**Comment by oganm** [comment]
Also it is not part of this pull request but instead of demanding pdftk address from the user it can be automatically detected

```r
    if(Sys.info()['sysname'] =='Windows'){
        path = system2('where','pdftk',stdout = TRUE)
    } else {
        path = system2('which','pdftk',stdout = TRUE)
    }
    animation::ani.options(pdftk = path)
```

**Comment by yulijia** [comment]
Thank you for your contribution and good example!

**Comment by yihui** [comment]
Should we just use `shQuote()`? I confess I haven't read my own source code in this package for several years...

**Comment by yulijia** [comment]
@yihui  you are right,  I will update it.

**Pull request merged**
